---
project:
  type: website
  preview:
    port: 4200
    browser: true
    watch-inputs: true
    navigate: true
    timeout: 300

format:
  html:
    search: true
    theme:
      light:
        - flatly
      dark:
        - darkly
    anchor-sections: true
    smooth-scroll: true
    code-link: true
    code-fold: true
    code-overflow: scroll
    code-line-numbers: true
    code-copy: true
    code-tools:
      source: true
      toggle: false
      caption: none
    code-block-bg: true
    code-block-border-left: "#1482FA"
    css: assets/css/style.scss
    number-sections: false
    lang: en-US
    page-layout: full

execute:
  freeze: auto
  cache: true
  code-line-numbers: true

knitr:
  opts_chunk:
    echo: true
    fig.width: 15

editor: visual
highlight-style: github

website:
  title: Biomarker Analysis Catalog
  image: assets/images/logo.png
  open-graph: true
  search:
    location: navbar
    type: overlay
    copy-button: true
  page-navigation: true
  reader-mode: true
  site-url: https://insightsengineering.github.io/biomarker-catalog
  repo-url: https://github.com/insightsengineering/biomarker-catalog
  repo-branch: main
  google-analytics: UA-125641273-1
  cookie-consent: true
  page-footer:
    left: |
      Made with ❤️ by the Statistical Engineering Team
  navbar:
    pinned: true
    collapse: false
    background: primary
    search: true
    right:
      - icon: slack
        href: https://app.slack.com/client/T028PB489D3/
        aria-label: Slack
      - icon: github
        href: https://github.com/insightsengineering/biomarker-catalog
        aria-label: Repository
  sidebar:
    - id: sidebar
      style: docked
      collapse-level: 1
      logo: assets/images/logo.png
      border: true
      contents:
        - text: Introduction
          file: index.qmd
        - text: "---"
        - file: tables/index.qmd
          text: Tables
          contents:
            - file: tables/cmt01.qmd
              text: CMT
              contents: 
                - file: tables/cmt01.qmd
                  text: CMT1
                - file: tables/CMT2/cmt02.qmd
                  text: CMT2
                  contents: 
                    - file: tables/CMT2/cmt02a.qmd
                      text: CMT2A
                - file: tables/cmt03.qmd
                  text: CMT3
            - file: tables/DT1/dt01.qmd
              text: DT
              contents: 
                - file: tables/DT1/dt01.qmd
                  text: DT1
                  contents: 
                    - file: tables/DT1/dt01a.qmd
                      text: DT1A
                    - file: tables/DT1/dt01b.qmd
                      text: DT1B
                    - file: tables/DT1/dt01c.qmd
                      text: DT1C
                - file: tables/DT2/dt02.qmd
                  text: DT2
                  contents: 
                    - file: tables/DT2/dt02a.qmd
                      text: DT2A
            - file: tables/TET1/tet01.qmd
              text: TET
              contents: 
                - file: tables/TET1/tet01.qmd
                  text: TET1
                  contents: 
                    - file: tables/TET1/tet01a.qmd
                      text: TET1A
        - text: "---"
        - file: graphs/index.qmd
          text: Graphs
          contents:
            - file: graphs/ag01.qmd
              text: AG
              contents: 
                - file: graphs/ag01.qmd
                  text: AG1
            - file: graphs/DG1/dg01.qmd
              text: DG
              contents: 
                - file: graphs/DG1/dg01.qmd
                  text: DG1
                  contents: 
                    - file: graphs/DG1/dg01a.qmd
                      text: DG1A
                    - file: graphs/DG1/dg01b.qmd
                      text: DG1B
                - file: graphs/dg02.qmd
                  text: DG2
                - file: graphs/DG3/dg03.qmd
                  text: DG3
                  contents: 
                    - file: graphs/DG3/dg03a.qmd
                      text: DG3A
                - file: graphs/dg04.qmd
                  text: DG4
            - file: graphs/KG1/kg01.qmd
              text: KG
              contents:     
                - file: graphs/KG1/kg01.qmd
                  text: KG1
                  contents: 
                    - file: graphs/KG1/kg01a.qmd
                      text: KG1A
                    - file: graphs/KG1/kg01b.qmd
                      text: KG1B
                - file: graphs/KG2/kg02.qmd
                  text: KG2
                  contents: 
                    - file: graphs/KG2/kg02a.qmd
                      text: KG2A
                - file: graphs/kg03.qmd
                  text: KG3
                - file: graphs/KG4/kg04.qmd
                  text: KG4
                  contents: 
                    - file: graphs/KG4/kg04a.qmd
                      text: KG4A
                    - file: graphs/KG4/kg04b.qmd
                      text: KG4B
                - file: graphs/KG5/kg05.qmd
                  text: KG5
                  contents: 
                    - file: graphs/KG5/kg05a.qmd
                      text: KG5A
                    - file: graphs/KG5/kg05b.qmd
                      text: KG5B
            - file: graphs/RFG1/rfg01.qmd
              text: RFG
              contents:     
                - file: graphs/RFG1/rfg01.qmd
                  text: RFG1
                  contents: 
                    - file: graphs/RFG1/rfg01a.qmd
                      text: RFG1A
                - file: graphs/RFG2/rfg02a.qmd
                  text: RFG2
                  contents: 
                    - file: graphs/RFG2/rfg02a.qmd
                      text: RFG2A
                    - file: graphs/RFG2/rfg02b.qmd
                      text: RFG2B
                    - file: graphs/RFG2/rfg02c.qmd
                      text: RFG2C
                - file: graphs/rfg03.qmd
                  text: RFG3
            - file: graphs/RG1/rg01.qmd
              text: RG
              contents:     
                - file: graphs/RG1/rg01.qmd
                  text: RG1
                  contents: 
                    - file: graphs/RG1/rg01a.qmd
                      text: RG1A
                    - file: graphs/RG1/rg01b.qmd
                      text: RG1B
                    - file: graphs/RG1/rg01c.qmd
                      text: RG1C
                - file: graphs/RG2/rg02.qmd
                  text: RG2
                  contents: 
                    - file: graphs/RG2/rg02a.qmd
                      text: RG2A
                - file: graphs/RG3/rg03.qmd
                  text: RG3
                  contents: 
                    - file: graphs/RG3/rg03a.qmd
                      text: RG3A
                    - file: graphs/RG3/rg03b.qmd
                      text: RG3B
            - file: graphs/spg01.qmd
              text: SPG
              contents:     
                - file: graphs/spg01.qmd
                  text: SPG1
                - file: graphs/spg02.qmd
                  text: SPG2
        - text: "---"
        - text: Index
          file: bac_index.qmd
  comments:
    giscus:
      # Reference: https://quarto.org/docs/reference/projects/books.html#giscus
      # Also https://giscus.app/ for all options
      repo: insightsengineering/biomarker-catalog
      repo-id: "R_kgDOJMeENQ"
      category: General
      category-id: "DIC_kwDOJMeENc4CVB9s"
      reactions-enabled: true
      theme: light
      language: en
      loading: lazy
      mapping: pathname
