---
title: Index
toc: true
toc-depth: 4
---

------------------------------------------------------------------------

### Tables

-   [CMT -- Cox Proportional Hazards Model Tables](./tables/cmt01.qmd)
    -   [CMT1 -- Cox Proportional Hazards Model Tables with a Single Covariate](./tables/cmt01.qmd)
    -   [CMT2 -- Cox Proportional Hazards Model Tables with Multiple Covariates](./tables/CMT2/cmt02.qmd)
    -   [CMT3 -- Cox Proportional Hazards Model Tables with Separate Models for Each Covariate](./tables/cmt03.qmd)
-   [DT -- Demographics Tables](./tables/DT1/dt01.qmd)
    -   [DT1 -- Demographics Tables Comparing BEP vs. Overall Population](./tables/DT1/dt01.qmd)
    -   [DT2 -- Demographics Tables Comparing BEP vs. non-BEP Population](./tables/DT2/dt02.qmd)
-   [TET -- Time-to-Event Summary Tables](./tables/TET1/tet01.qmd)
    -   [TET1 -- Time-to-Event Summary Tables](./tables/TET1/tet01.qmd)

### Graphs

-   [AG -- Utilities for All Graphs](./graphs/ag01.qmd)
-   [DG -- Histograms, Barplots, Scatterplots](./graphs/DG1/dg01.qmd)
    -   [DG1 -- Histograms of Numeric Variables](./graphs/DG1/dg01.qmd)
    -   [DG2 -- Boxplots of a Numeric Variable by Categorical Variables](./graphs/dg02.qmd)
    -   [DG3 -- Barplots of Categorical Variables](./graphs/DG3/dg03.qmd)
    -   [DG4 -- Scatterplots of Two Numerical Variables](./graphs/dg04.qmd)
-   [KG -- Kaplan-Meier Graphs](./graphs/KG1/kg01.qmd)
    -   [KG1 -- Kaplan-Meier Graphs for One Treatment Arm](./graphs/KG1/kg01.qmd)
    -   [KG2 -- Kaplan-Meier Graphs by Treatment Arm](./graphs/KG2/kg02.qmd)
    -   [KG3 -- Kaplan-Meier Graphs by Biomarker Subgroups](./graphs/kg03.qmd)
    -   [KG4 -- Kaplan-Meier Graphs by Treatment Arm and Biomarker Subgroups](./graphs/KG4/kg04.qmd)
    -   [KG5 -- Kaplan-Meier Graphs by Treatment Arm and Continuous Biomarker Cut](./graphs/KG5/kg05.qmd)
-   [RFG -- Response Forest Graphs](./graphs/RFG1/rfg01.qmd)
    -   [RFG1 -- Response Forest Graphs for Comparing Treatment Effects Across Subgroups](./graphs/RFG1/rfg01.qmd)
    -   [RFG2 -- Response Forest Graphs for Comparing Continuous Biomarker Effects Across Subgroups](./graphs/RFG2/rfg02a.qmd)
    -   [RFG3 -- Response Forest Graphs Within Treatment Arms by Continuous Biomarker Cutoff](./graphs/rfg03.qmd)
-   [RG -- Response Graphs](./graphs/RG1/rg01.qmd)
    -   [RG1 -- Response Graphs for Overall Population](./graphs/RG1/rg01.qmd)
    -   [RG2 -- Response Graphs by Treatment Arms](./graphs/RG2/rg02.qmd)
    -   [RG3 -- Response Graphs Comparing BEP vs. Overall Population](./graphs/RG3/rg03.qmd)
-   [RNAG -- RNAseq Graphs](./graphs/rnag01.qmd)
    -   [RNAG1 -- RNAseq QC Graphs](./graphs/rnag01.qmd)
    -   [RNAG2 -- RNAseq Top Genes Plot](./graphs/rnag02.qmd)
    -   [RNAG3 -- RNAseq PCA Graphs](./graphs/rnag03.qmd)
    -   [RNAG4 -- RNAseq Sample Correlation Graph](./graphs/rnag04.qmd)
    -   [RNAG5 -- RNAseq Differential Gene Expression Analysis](./graphs/rnag05.qmd)
    -   [RNAG6 -- RNAseq Barplot](./graphs/rnag01.qmd)
    -   [RNAG7 -- RNAseq Boxplot](./graphs/rnag01.qmd)
    -   [RNAG8 -- RNAseq Scatterplot](./graphs/rnag01.qmd)
    -   [RNAG9 -- RNAseq Kaplan-Meier Graph](./graphs/rnag01.qmd)
    -   [RNAG10 -- RNAseq Survival Forest Graph](./graphs/rnag01.qmd)
-   [SFG -- Survival Forest Graphs](./graphs/SFG1/sfg01.qmd)
    -   [SFG1 -- Survival Forest Graphs for Overall Population and by Categorical Biomarker](./graphs/SFG1/sfg01.qmd)
    -   [SFG2 -- Survival Forest Graphs for Overall Population and by Percentiles of Continuous Biomarker](./graphs/SFG2/sfg02.qmd)
    -   [SFG3 -- Survival Forest Graphs for One Treatment Arm](./graphs/SFG3/sfg03.qmd)
    -   [SFG4 -- Survival Forest Graphs Within Treatment Arms by Continuous Biomarker Cutoff](./graphs/sfg04.qmd)
    -   [SFG5 -- Survival Forest Graphs Comparing on Subgroups](./graphs/SFG5/sfg05.qmd)
    -   [SFG6 -- Survival Forest Graphs Comparing on Subgroups](./graphs/SFG6/sfg06a.qmd)
-   [SPG -- STEP Graphs](./graphs/spg01.qmd)
    -   [SPG1 -- STEP Graphs for Survival Outcome](./graphs/spg01.qmd)
    -   [SPG2 -- STEP Graphs for Response Outcome](./graphs/spg02.qmd)
