---
exclude-listing: true
---

## Setup

These templates are helpful when we are interested in modelling the effects of continuous biomarker variables on a time-to-event (survival) outcome, conditional on covariates and/or stratification variables included in Cox proportional hazards regression models.
We would like to assess how the estimates effects change when we look at different subgroups.

In detail the differences to the other survival forest graphs ([SFG1](../../graphs/SFG1/sfg01.qmd) to [SFG5](../../graphs/SFG5/sfg05.qmd)) are the following:

-   The `extract_survival_subgroups()` and `tabulate_survival_subgroups()` functions evaluate the treatment effects comparing two arms, across subgroups. On the other hand, the `extract_survival_biomarkers()` and `tabulate_survival_biomarkers()` functions used here in SFG6 evaluate the effects from continuous biomarkers in the Cox proportional hazards models, across subgroups.
-   The `extract_survival_subgroups()` and `tabulate_survival_subgroups()` functions only allow specification of a single treatment arm variable, while the `extract_survival_biomarkers()` and `tabulate_survival_biomarkers()` allow to look at multiple continuous biomarker variables at once.
-   In addition to the treatment arms, the use of `extract_survival_subgroups()` and `tabulate_survival_subgroups()` functions can be extended to other binary variables, as done in [SFG3](../../graphs/SFG3/sfg03.qmd) and [SFG4](../../graphs/sfg04.qmd). For example, we could define the binarized `ARM` variable as `AGE>=65` vs. `AGE<65` and then look at the odds ratios across subgroups. For the `extract_survival_biomarkers()` and `tabulate_survival_biomarkers()` functions, we could use the original continuous biomarker variable `AGE`, and then look at the estimated effect across subgroups.

Similarly like in [SFG3](../../graphs/SFG3/sfg03.qmd), we will use the `cadtte` data set from the `random.cdisc.data` package.
Here we just filter for the overall survival outcome in a single arm in the biomarker evaluable population.

```{r, message = FALSE}
library(tern)
library(dplyr)

adtte_f <- random.cdisc.data::cadtte %>%
  df_explicit_na() %>%
  filter(
    PARAMCD == "OS",
    ARM == "A: Drug X",
    BEP01FL == "Y"
  ) %>%
  mutate(
    AVAL = day2month(AVAL),
    AVALU = "Months",
    is_event = CNSR == 0
  ) %>%
  var_relabel(
    BEP01FL = "BEP",
    BMRKR1 = "Biomarker (Countinuous)"
  )
```
