---
exclude-listing: true
---

## Setup

These templates are helpful when we are interested in the odds ratios between two groups, usually two treatment arms.
We would like to assess how the odds ratio changes when we look at different subgroups, often defined by categorical biomarker variables, e.g.

We will use the `cadrs` data set from the `random.cdisc.data` package to create the response forest graph.
We start by filtering the `adrs` data set for the Best Confirmed Overall Response by Investigator and patients with measurable disease at baseline `(BMEASIFL == "Y")`.
We create a new variable for response information (we define response patients to include CR and PR patients), and binarize the `ARM` variable.
We also fix a data artifact by setting the categorical biomarker variable `BMRKR2` to an explicit `<Missing>` level for the non-biomarker evaluable population.

We also relabel the biomarker evaluable population flag variable `BEP01FL` and the categorical biomarker variable `BMRKR2` to update the display label of these variables in the graph.

```{r, message = FALSE}
library(tern)
library(ggplot2.utils)
library(dplyr)

adrs <- random.cdisc.data::cadrs %>%
  df_explicit_na() %>%
  filter(PARAMCD == "BESRSPI", BMEASIFL == "Y") %>%
  mutate(
    is_rsp = AVALC %in% c("CR", "PR"),
    ARM_BIN = fct_collapse_only(
      ARM,
      CTRL = c("B: Placebo"),
      TRT = c("A: Drug X", "C: Combination")
    ),
    BMRKR2 = fct_explicit_na_if(BMRKR2, BEP01FL == "N")
  ) %>%
  var_relabel(
    BEP01FL = "BEP",
    BMRKR2 = "Biomarker (Categorical)"
  )
```
